"""NIST Table 4 compounds. Generated by pyradiate.tools.nist.lib_builder. Do not edit."""

from dataclasses import dataclass
from enum import Enum


@dataclass(frozen=True)
class Compound:
    name: str
    nist_id: str


class Compounds(Enum):
    @property
    def name(self):
        return self.value.name

    @property
    def nist_id(self):
        return self.value.nist_id

    A150_TISSUE_EQUIVALENT_PLASTIC = Compound("A-150 Tissue-Equivalent Plastic", "a150")
    ADIPOSE_TISSUE = Compound("Adipose Tissue (ICRU-44)", "adipose")
    AIR_DRY = Compound("Air, Dry (near sea level)", "air")
    ALANINE = Compound("Alanine", "alanine")
    B100_BONE_EQUIVALENT_PLASTIC = Compound("B-100 Bone-Equivalent Plastic", "b100")
    BAKELITE = Compound("Bakelite", "bakelite")
    BLOOD_WHOLE = Compound("Blood, Whole (ICRU-44)", "blood")
    BONE_CORTICAL = Compound("Bone, Cortical (ICRU-44)", "bone")
    BRAIN_GREY_WHITE_MATTER = Compound("Brain, Grey/White Matter (ICRU-44)", "brain")
    BREAST_TISSUE = Compound("Breast Tissue (ICRU-44)", "breast")
    C552_AIR_EQUIVALENT_PLASTIC = Compound("C-552 Air-equivalent Plastic", "c552")
    CADMIUM_TELLURIDE = Compound("Cadmium Telluride", "telluride")
    CALCIUM_FLUORIDE = Compound("Calcium Fluoride", "fluoride")
    CALCIUM_SULFATE = Compound("Calcium Sulfate", "calcium")
    CERIC_AMMONIUM_SULFATE_SOLUTION = Compound("15 mmol L-1 Ceric Ammonium Sulfate Solution", "ceric")
    CESIUM_IODIDE = Compound("Cesium Iodide", "cesium")
    CONCRETE_BARITE = Compound("Concrete, Barite (Type BA)", "concreteba")
    CONCRETE_ORDINARY = Compound("Concrete, Ordinary", "concrete")
    EYE_LENS = Compound("Eye Lens (ICRU-44)", "eye")
    FERROUS_SULFATE_STANDARD_FRICKE = Compound("Ferrous Sulfate, Standard Fricke", "fricke")
    GADOLINIUM_OXYSULFIDE = Compound("Gadolinium Oxysulfide", "gadolinium")
    GAFCHROMIC_SENSOR = Compound("Gafchromic Sensor", "gafchromic")
    GALLIUM_ARSENIDE = Compound("Gallium Arsenide", "gallium")
    GLASS_BOROSILICATE_PYREX = Compound('Glass, Borosilicate "Pyrex"', "pyrex")
    GLASS_LEAD = Compound("Glass, Lead", "glass")
    LITHIUM_FLUORIDE = Compound("Lithium Fluoride", "lithiumflu")
    LITHIUM_TETRABORATE = Compound("Lithium Tetraborate", "lithium")
    LUNG_TISSUE = Compound("Lung Tissue (ICRU-44)", "lung")
    MAGNESIUM_TETRABORATE = Compound("Magnesium Tetraborate", "magnesium")
    MERCURIC_IODIDE = Compound("Mercuric Iodide", "mercuric")
    MUSCLE_SKELETAL = Compound("Muscle, Skeletal (ICRU-44)", "muscle")
    OVARY = Compound("Ovary (ICRU-44)", "ovary")
    PHOTOGRAPHIC_EMULSION_KODAK_TYPE_AA = Compound("Photographic Emulsion, Kodak Type AA", "kodak")
    PHOTOGRAPHIC_EMULSION_STANDARD_NUCLEAR = Compound("Photographic Emulsion, Standard Nuclear", "photoemul")
    PLASTIC_SCINTILLATOR_VINYLTOLUENE = Compound("Plastic Scintillator, Vinyltoluene", "vinyl")
    POLYETHYLENE = Compound("Polyethylene", "polyethylene")
    POLYETHYLENE_TEREPHTHALATE_MYLAR = Compound('Polyethylene Terephthalate, "Mylar"', "mylar")
    POLYMETHYL_METHACRYLATE = Compound("Polymethyl Methacrylate", "pmma")
    POLYSTYRENE = Compound("Polystyrene", "polystyrene")
    POLYTETRAFLUOROETHYLENE_TEFLON = Compound('Polytetrafluoroethylene, "Teflon"', "teflon")
    POLYVINYL_CHLORIDE = Compound("Polyvinyl Chloride", "polyvinyl")
    RADIOCHROMIC_DYE_FILM_NYLON_BASE = Compound("Radiochromic Dye Film, Nylon Base", "nylonfilm")
    TESTIS = Compound("Testis (ICRU-44)", "testis")
    TISSUE_EQUIVALENT_GAS_METHANE_BASED = Compound("Tissue-Equivalent Gas, Methane Based", "temethane")
    TISSUE_EQUIVALENT_GAS_PROPANE_BASED = Compound("Tissue-Equivalent Gas, Propane Based", "tepropane")
    TISSUE_SOFT = Compound("Tissue, Soft (ICRU-44)", "tissue")
    TISSUE_SOFT_ICRU_FOUR_COMPONENT = Compound("Tissue, Soft (ICRU Four-Component)", "tissue4")
    WATER_LIQUID = Compound("Water, Liquid", "water")
